alter table SAAD.ANDAMENTO_DOCUMENTO
   drop foreign key FK_ANDO_DOUN;

alter table SAAD.ANDAMENTO_DOCUMENTO
   drop foreign key FK_ANDO_USUARIO;

alter table SAAD.ANEXO
   drop foreign key FK_ANEXO_DOCUMENTO_UNIDADE;

alter table SAAD.AVISO_UNIDADE
   drop foreign key FK_AVUN_DOCUMENTO_UNIDADE;

alter table SAAD.AVISO_UNIDADE
   drop foreign key FK_AVUN_LOCAL;

alter table SAAD.CAMPO_PERSONALIZADO
   drop foreign key FK_CAPE_TIDO;

alter table SAAD.CONTROLE_NUMERACAO
   drop foreign key FK_CONTROLE_NUMERACAO_LOCAL;

alter table SAAD.CONTROLE_NUMERACAO
   drop foreign key FK_CONTROLE_NUMERACAO_TIDU;

alter table SAAD.DESTINATARIO_AVISO
   drop foreign key FK_DEAV_AVISO_UNIDADE;

alter table SAAD.DESTINATARIO_AVISO
   drop foreign key FK_DESTINATARIO_AVISO_USUARIO;

alter table SAAD.DESTINATARIO_DOCUMENTO
   drop foreign key FK_DEDO_LOCAL;

alter table SAAD.DESTINATARIO_DOCUMENTO
   drop foreign key FK_DEDO_TRATAMENTO;

alter table SAAD.DESTINATARIO_DOCUMENTO
   drop foreign key FK_DEST_DOCUMENTO_UNIDADE;

alter table SAAD.DOCUMENTO_UNIDADE
   drop foreign key FK_DOCUMENTO_UNIDADE_LOCAL;

alter table SAAD.DOCUMENTO_UNIDADE
   drop foreign key FK_DOCUMENTO_UNIDADE_PROCESSO;

alter table SAAD.DOCUMENTO_UNIDADE
   drop foreign key FK_DOUN_DESTINATARIO;

alter table SAAD.DOCUMENTO_UNIDADE
   drop foreign key FK_DOUN_ENDERECAMENTO;

alter table SAAD.DOCUMENTO_UNIDADE
   drop foreign key FK_DOCUMENTO_TIPO_DOCUMENTO;

alter table SAAD.ENDERECAMENTO_EXTERNO
   drop foreign key FK_ENEX_DESTINATARIO;

alter table SAAD.ENDERECAMENTO_EXTERNO
   drop foreign key FK_ENEX_ENDERECAMENTO;

alter table SAAD.ENDERECAMENTO_INTERNO
   drop foreign key FK_ENIN_ENDERECAMENTO;

alter table SAAD.ENDERECAMENTO_INTERNO
   drop foreign key FK_ENIN_LOCAL;

alter table SAAD.EVENTO
   drop foreign key FK_DOEV_DOUN;

alter table SAAD.METADADO_AUTORIZADO
   drop foreign key FK_MEAU_CAPE;

alter table SAAD.METADADO_AUTORIZADO
   drop foreign key F_FK_MEAU_LOCAL;

alter table SAAD.RESERVA_NUMERACAO_DOC
   drop foreign key FK_REND_DOUN;

alter table SAAD.RESERVA_NUMERACAO_DOC
   drop foreign key FK_REND_LOCAL;

alter table SAAD.RESERVA_NUMERACAO_DOC
   drop foreign key FK_REND_TIDU;

alter table SAAD.TAREFA_DEMANDA_DOCUMENTO
   drop foreign key FK_TADD_DOCUMENTO_UNIDADE;

alter table SAAD.TAREFA_DEMANDA_DOCUMENTO
   drop foreign key FK_TADD_USUARIO;

alter table SAAD.TIPO_DOCUMENTO_UNIDADE
   drop foreign key F_FK_TIDU_LOCAL;

alter table SAAD.TIPO_DOCUMENTO_UNIDADE
   drop foreign key FK_TIDU_TIDO;

alter table SAAD.VALOR_METADADO
   drop foreign key FK_VAME_DOUN;

alter table SAAD.VALOR_METADADO
   drop foreign key FK_VAME_MEAU;

drop index SAAD.IX_ANDO_SQ_DOCUMEN;

drop index SAAD.IX_ANDO_SEQ_USUARI;

drop table SAAD.ANDAMENTO_DOCUMENTO;

drop index SAAD.IX_ANEXO_SQ_DOCUME;

drop table SAAD.ANEXO;

drop table SAAD.AUDIT_DOCUMENTO_UNIDADE;

drop index SAAD.IX_AVUN_SEQ_LOCAL;

drop index SAAD.IX_AVUN_SQ_DOCUMEN;

drop table SAAD.AVISO_UNIDADE;

drop index SAAD.IX_CAPE_SQ_TIPO_DO;

drop table SAAD.CAMPO_PERSONALIZADO;

drop index SAAD.IX_CONU_SEQ_LOCAL;

drop table SAAD.CONTROLE_NUMERACAO;

drop index SAAD.IX_DEAV_SEQ_USUARI;

drop table SAAD.DESTINATARIO_AVISO;

drop index SAAD.IX_DEDO_SEQ_TRATAM;

drop index SAAD.IX_DEDO_SEQ_LOCAL;

drop table SAAD.DESTINATARIO_DOCUMENTO;

drop index SAAD.IX_DOUN_SEQ_DESTIN;

drop index SAAD.IX_DOUN_NUM_REGIST;

drop index SAAD.IX_DOUN_SQ_ENDEREC;

drop index SAAD.IX_DOUN_SEQ_LOCAL;

drop index SAAD.IX_DOUN_SQ_TIPO_DO;

drop table SAAD.DOCUMENTO_UNIDADE;

drop table SAAD.ENDERECAMENTO;

drop index SAAD.IX_ENEX_SQ_DESTINA;

drop index SAAD.IX_ENEX_SEQ_DESTIN;

drop table SAAD.ENDERECAMENTO_EXTERNO;

drop index SAAD.IX_ENIN_SEQ_LOCAL;

drop table SAAD.ENDERECAMENTO_INTERNO;

drop table SAAD.EVENTO;

drop index SAAD.IX_MEAU_SEQ_LOCAL;

drop table SAAD.METADADO_AUTORIZADO;

drop index SAAD.IX_RENU_SEQ_LOCAL;

drop index SAAD.IX_RENU_SQ_DOCUMEN;

drop index SAAD.IX_RENU_SQ_TIPO_DO;

drop table SAAD.RESERVA_NUMERACAO_DOC;

drop index SAAD.IX_TADD_SEQ_USUARI;

drop index SAAD.IX_TADD_SQ_DOCUMEN;

drop table SAAD.TAREFA_DEMANDA_DOCUMENTO;

drop table SAAD.TIPO_DOCUMENTO;

drop index SAAD.IX_TIDU_SEQ_LOCAL;

drop table SAAD.TIPO_DOCUMENTO_UNIDADE;

drop index SAAD.IX_VAME_SQ_CAMPO_P;

drop table SAAD.VALOR_METADADO;

--==============================================================
-- Table: ANDAMENTO_DOCUMENTO
--==============================================================
create table SAAD.ANDAMENTO_DOCUMENTO
(
   SQ_ANDAMENTO_DOCUMENTO INTEGER                not null generated by default as identity,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   SEQ_USUARIO          INTEGER                not null,
   DS_ANDAMENTO_DOCUMENTO CLOB(2097152)          not null,
   DH_ANDAMENTO_DOCUMENTO DATE                   not null,
   constraint PK_ANDAMENTO_DOCUMENTO primary key (SQ_ANDAMENTO_DOCUMENTO)
);

comment on column SAAD.ANDAMENTO_DOCUMENTO.SQ_ANDAMENTO_DOCUMENTO is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.ANDAMENTO_DOCUMENTO.SQ_DOCUMENTO_UNIDADE is
'Definição de chave estrangeira. Tabela DOCUMENTO_UNIDADE.';

comment on column SAAD.ANDAMENTO_DOCUMENTO.SEQ_USUARIO is
'Representa o vínculo com o SEQ_USUARIO do banco JUSTIÇA COMUNS.';

comment on column SAAD.ANDAMENTO_DOCUMENTO.DS_ANDAMENTO_DOCUMENTO is
'Descrição do andamento do documento.';

comment on column SAAD.ANDAMENTO_DOCUMENTO.DH_ANDAMENTO_DOCUMENTO is
'Data do andamento do documento.';

--==============================================================
-- Index: IX_ANDO_SEQ_USUARI
--==============================================================
create index SAAD.IX_ANDO_SEQ_USUARI on SAAD.ANDAMENTO_DOCUMENTO (
   SEQ_USUARIO          ASC
);

--==============================================================
-- Index: IX_ANDO_SQ_DOCUMEN
--==============================================================
create index SAAD.IX_ANDO_SQ_DOCUMEN on SAAD.ANDAMENTO_DOCUMENTO (
   SQ_DOCUMENTO_UNIDADE ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.ANDAMENTO_DOCUMENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: ANEXO
--==============================================================
create table SAAD.ANEXO
(
   SQ_ANEXO             INT                    not null generated by default as identity,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   NM_ARQUIVO           VARCHAR(150)           not null,
   constraint PK_ANEXO primary key (SQ_ANEXO)
);

comment on column SAAD.ANEXO.SQ_ANEXO is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.ANEXO.SQ_DOCUMENTO_UNIDADE is
'Definição de chave estrangeira. Tabela DOCUMENTO_UNIDADE.';

comment on column SAAD.ANEXO.NM_ARQUIVO is
'Nome do arquivo anexo.';

--==============================================================
-- Index: IX_ANEXO_SQ_DOCUME
--==============================================================
create index SAAD.IX_ANEXO_SQ_DOCUME on SAAD.ANEXO (
   SQ_DOCUMENTO_UNIDADE ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.ANEXO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: AUDIT_DOCUMENTO_UNIDADE
--==============================================================
create table SAAD.AUDIT_DOCUMENTO_UNIDADE
(
   SQ_AUDIT_DOCUMENTO_UNIDADE INTEGER                not null,
   SEQ_USUARIO          INTEGER                not null,
   DH_OPERACAO          DATE                   not null,
   TP_OPERACAO          CHAR(1)                not null
      constraint CK_AUDU_TP_OPERACAO check (TP_OPERACAO in ('I','E','A')),
   SQ_DOCUMENTO_UNIDADE INTEGER                not null generated by default as identity,
   SQ_TIPO_DOCUMENTO_UNIDADE INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   NUM_REGISTRO         CHARACTER(12),
   SQ_ENDERECAMENTO     INTEGER,
   TP_CLASSIFICACAO_DOCUMENTO CHAR(1)                not null
      constraint CK_AUDU_TP_CLASSIFICACAO check (TP_CLASSIFICACAO_DOCUMENTO in ('E','R')),
   TP_ORIGEM            CHAR(1)                not null
      constraint CK_AUDU_TP_ORIGEM check (TP_ORIGEM in ('I','E')),
   ID_DOCUMENTO_STJ     VARCHAR(6)             not null,
   NR_DOCUMENTO_ORIGEM  VARCHAR(20)            not null,
   DH_DOCUMENTO_ORIGEM  DATE                   not null,
   DH_RECEBIMENTO_EXPEDICAO DATE,
   DH_INCLUSAO          DATE,
   NR_PROCESSO_ADMINISTRATIVO VARCHAR(30),
   TX_ASSUNTO_DOCUMENTO CLOB(2096)             not null,
   ST_DOCUMENTO_EVENTO  CHAR(1)                not null default 'N'
      constraint CK_AUDU_ST_DOCUMENTO_EVENTO check (ST_DOCUMENTO_EVENTO in ('S','N')),
   ST_SITUACAO_DOCUMENTO CHAR(1)                not null default 'P'
      constraint CK_AUDU_ST_SITUACAO_DOCUMENTO check (ST_SITUACAO_DOCUMENTO in ('P','R','S','C')),
   SEQ_DESTINATARIO     INTEGER,
   constraint PK_AUDIT_DOCUMENTO_UNIDADE primary key (SQ_AUDIT_DOCUMENTO_UNIDADE)
);

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SEQ_LOCAL is
'Sequencial do local (atribuido automaticamente).';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.ST_DOCUMENTO_EVENTO is
'SABE TEM OU NAO EVENTO ASSOCIADO. Ex: reuniao,palestra, convite';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.AUDIT_DOCUMENTO_UNIDADE to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: AVISO_UNIDADE
--==============================================================
create table SAAD.AVISO_UNIDADE
(
   SQ_AVISO_UNIDADE     INTEGER                not null generated by default as identity,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   SEQ_LOCAL            INTEGER                not null,
   TP_ENDERECAMENTO_AVISO CHAR(1)                not null
      constraint CK_AVUN_TP_ENDERECAMENTO_AVISO check (TP_ENDERECAMENTO_AVISO in ('I','U','M')),
   DS_AVISO_UNIDADE     CLOB(2056)             not null,
   ST_AVISO_UNIDADE     CHAR(1)                not null
      constraint CK_AVUN_ST_AVISO_UNIDADE check (ST_AVISO_UNIDADE in ('N','L','P','R','E','S')),
   DT_INCLUSAO          DATE,
   DT_RESOLUSAO         DATE,
   constraint PK_AVISO_UNIDADE primary key (SQ_AVISO_UNIDADE)
);

comment on column SAAD.AVISO_UNIDADE.SQ_AVISO_UNIDADE is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.AVISO_UNIDADE.SQ_DOCUMENTO_UNIDADE is
'Definição de chave estrangeira. Tabela DOCUEMENTO_AVISO.';

comment on column SAAD.AVISO_UNIDADE.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

comment on column SAAD.AVISO_UNIDADE.TP_ENDERECAMENTO_AVISO is
'Indica 
I - INDIVIDUAL - Somente um destinátario
M - MULTIPLO - Mais de um destinatario
U - UNIDADE  - Para todas os lotados na unidade

';

comment on column SAAD.AVISO_UNIDADE.DS_AVISO_UNIDADE is
'Descrição do aviso.';

comment on column SAAD.AVISO_UNIDADE.ST_AVISO_UNIDADE is
'Indica a situação definida para a unidade do aviso.
N - NAO LIDO
L - LIDO
P - PENDENTE
R - RESOLVIDO
E - EM ANDAMENTO
S - SUSPENSO';

comment on column SAAD.AVISO_UNIDADE.DT_INCLUSAO is
'Data de inclusão do aviso.';

comment on column SAAD.AVISO_UNIDADE.DT_RESOLUSAO is
'Data de resolução do aviso.';

--==============================================================
-- Index: IX_AVUN_SQ_DOCUMEN
--==============================================================
create index SAAD.IX_AVUN_SQ_DOCUMEN on SAAD.AVISO_UNIDADE (
   SQ_DOCUMENTO_UNIDADE ASC
);

--==============================================================
-- Index: IX_AVUN_SEQ_LOCAL
--==============================================================
create index SAAD.IX_AVUN_SEQ_LOCAL on SAAD.AVISO_UNIDADE (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.AVISO_UNIDADE to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: CAMPO_PERSONALIZADO
--==============================================================
create table SAAD.CAMPO_PERSONALIZADO
(
   SQ_CAMPO_PERSONALIZADO NUMERIC(6, 0)          not null generated by default as identity,
   SQ_TIPO_DOCUMENTO    INTEGER                not null,
   NM_CAMPO_PERSONALIZADO VARCHAR(30)            not null,
   TP_CAMPO_PERSONALIZADO CHAR(2)                not null
      constraint CK_CAPE_TP_CAMPO_PERSONALIZADO check (TP_CAMPO_PERSONALIZADO in ('CA','BO','IN','DT','HR','DH','MN')),
   VR_TAMANHO_CAMPO     INTEGER                not null,
   constraint PK_CAMPO_PERSONALIZADO primary key (SQ_CAMPO_PERSONALIZADO)
);

--==============================================================
-- Index: IX_CAPE_SQ_TIPO_DO
--==============================================================
create index SAAD.IX_CAPE_SQ_TIPO_DO on SAAD.CAMPO_PERSONALIZADO (
   SQ_TIPO_DOCUMENTO    ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.CAMPO_PERSONALIZADO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: CONTROLE_NUMERACAO
--==============================================================
create table SAAD.CONTROLE_NUMERACAO
(
   SQ_TIPO_DOCUMENTO    INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   NR_ANO               INTEGER                not null,
   VR_ULTIMO_NUMERO     INTEGER                not null,
   constraint PK_CONTROLE_NUMERACAO primary key (SQ_TIPO_DOCUMENTO, SEQ_LOCAL, NR_ANO)
);

comment on column SAAD.CONTROLE_NUMERACAO.SQ_TIPO_DOCUMENTO is
'Definicao de chave estrangeira. Tabela TIPO_DOCUMENTO';

comment on column SAAD.CONTROLE_NUMERACAO.SEQ_LOCAL is
'Sequencial do local (atribuido automaticamente).';

comment on column SAAD.CONTROLE_NUMERACAO.NR_ANO is
'Número do Ano em que foi criado o documento.';

comment on column SAAD.CONTROLE_NUMERACAO.VR_ULTIMO_NUMERO is
'Apresenta o valor do último número do documento gerado pelo sistema. ';

--==============================================================
-- Index: IX_CONU_SEQ_LOCAL
--==============================================================
create index SAAD.IX_CONU_SEQ_LOCAL on SAAD.CONTROLE_NUMERACAO (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.CONTROLE_NUMERACAO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: DESTINATARIO_AVISO
--==============================================================
create table SAAD.DESTINATARIO_AVISO
(
   SQ_AVISO_UNIDADE     INTEGER                not null,
   SEQ_USUARIO          INTEGER                not null,
   ST_AVISO_DESTINATARIO CHAR(1)               
      constraint CK_AVDE_ST_AVISO_DESTINATARIO check (ST_AVISO_DESTINATARIO is null or (ST_AVISO_DESTINATARIO in ('N','L','P','R','E','S'))),
   constraint PK_DESTINATARIO_AVISO primary key (SQ_AVISO_UNIDADE, SEQ_USUARIO)
);

comment on column SAAD.DESTINATARIO_AVISO.SQ_AVISO_UNIDADE is
'Definição de chave estrangeira. Tabela AVISO_UNIDADE';

comment on column SAAD.DESTINATARIO_AVISO.SEQ_USUARIO is
'Representa o vínculo com o SEQ_USUARIO do banco JUSTIÇA COMUNS.';

comment on column SAAD.DESTINATARIO_AVISO.ST_AVISO_DESTINATARIO is
'Indica a situação definida pelo destinatário do aviso.
N - NAO LIDO
L - LIDO
P - PENDENTE
R - RESOLVIDO
E - EM ANDAMENTO
S - SUSPENSO';

--==============================================================
-- Index: IX_DEAV_SEQ_USUARI
--==============================================================
create index SAAD.IX_DEAV_SEQ_USUARI on SAAD.DESTINATARIO_AVISO (
   SEQ_USUARIO          ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.DESTINATARIO_AVISO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: DESTINATARIO_DOCUMENTO
--==============================================================
create table SAAD.DESTINATARIO_DOCUMENTO
(
   SQ_DESTINATARIO_DOCUMENTO INTEGER                not null,
   NM_DESTINATARIO      VARCHAR(150),
   NM_ENDERECO          VARCHAR(72),
   NM_COMPLEMENTO_ENDERECO VARCHAR(72),
   NM_BAIRRO            VARCHAR(50),
   NR_CEP               CHARACTER(8),
   NM_CIDADE            VARCHAR(100),
   SG_UF                CHARACTER(2),
   NR_TELEFONE          VARCHAR(70),
   DT_ANIVERSARIO       DATE,
   NM_EMAIL             VARCHAR(72),
   NM_FAX               VARCHAR(70),
   NM_TITULO            VARCHAR(72),
   SEQ_LOCAL            INTEGER,
   SEQ_TRATAMENTO       INTEGER,
   TP_SEXO              CHARACTER(1)          
      constraint C_TP_SEXO check (TP_SEXO is null or (TP_SEXO in ('M','F'))),
   constraint DETO_PK primary key (SQ_DESTINATARIO_DOCUMENTO)
);

--==============================================================
-- Index: IX_DEDO_SEQ_LOCAL
--==============================================================
create index SAAD.IX_DEDO_SEQ_LOCAL on SAAD.DESTINATARIO_DOCUMENTO (
   SEQ_LOCAL            ASC
);

--==============================================================
-- Index: IX_DEDO_SEQ_TRATAM
--==============================================================
create index SAAD.IX_DEDO_SEQ_TRATAM on SAAD.DESTINATARIO_DOCUMENTO (
   SEQ_TRATAMENTO       ASC
);

grant CONTROL on SAAD.DESTINATARIO_DOCUMENTO to DB2PRO;

grant ALTER,DELETE,INDEX,INSERT,SELECT,REFERENCES,UPDATE on SAAD.DESTINATARIO_DOCUMENTO to DB2PRO with grant option;

grant DELETE,INSERT,REFERENCES,SELECT,UPDATE on SAAD.DESTINATARIO_DOCUMENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: DOCUMENTO_UNIDADE
--==============================================================
create table SAAD.DOCUMENTO_UNIDADE
(
   SQ_DOCUMENTO_UNIDADE INTEGER                not null generated by default as identity,
   SQ_TIPO_DOCUMENTO    INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   NUM_REGISTRO         CHARACTER(12),
   SQ_ENDERECAMENTO     INTEGER,
   TP_CLASSIFICACAO_DOCUMENTO CHAR(1)                not null
      constraint CK_DOUN_TP_CLASSIFICACAO check (TP_CLASSIFICACAO_DOCUMENTO in ('E','R')),
   TP_ORIGEM            CHAR(1)                not null
      constraint CK_DOUN_TP_ORIGEM check (TP_ORIGEM in ('I','E')),
   ID_DOCUMENTO_STJ     VARCHAR(6)             not null,
   NR_DOCUMENTO_ORIGEM  VARCHAR(20)            not null,
   DT_DOCUMENTO_ORIGEM  DATE                   not null,
   DT_RECEBIMENTO_EXPEDICAO DATE,
   DH_INCLUSAO_DOCUMENTO TIMESTAMP,
   NR_PROCESSO_ADMINISTRATIVO VARCHAR(30),
   TX_ASSUNTO_DOCUMENTO CLOB(2097152)          not null,
   ST_DOCUMENTO_EVENTO  CHAR(1)                not null default 'N'
      constraint CK_DOUN_ST_DOCUMENTO_EVENTO check (ST_DOCUMENTO_EVENTO in ('S','N')),
   ST_SITUACAO_DOCUMENTO CHAR(1)                not null default 'P'
      constraint CK_DOUN_ST_SITUACAO_DOCUMENTO check (ST_SITUACAO_DOCUMENTO in ('P','R','S','C')),
   SEQ_DESTINATARIO     INTEGER,
   constraint PK_DOCUMENTO_UNIDADE primary key (SQ_DOCUMENTO_UNIDADE)
);

comment on column SAAD.DOCUMENTO_UNIDADE.SQ_DOCUMENTO_UNIDADE is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.DOCUMENTO_UNIDADE.SQ_TIPO_DOCUMENTO is
'Definição de chave estrangeira. Tabela TIPO_DOCUMENTO_UNIDADE.';

comment on column SAAD.DOCUMENTO_UNIDADE.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

comment on column SAAD.DOCUMENTO_UNIDADE.NUM_REGISTRO is
'Número do registro do documento gerado pelo sistema.';

comment on column SAAD.DOCUMENTO_UNIDADE.SQ_ENDERECAMENTO is
'Definicao de chave estrangeira. Tabela ENDERECAMENTO';

comment on column SAAD.DOCUMENTO_UNIDADE.TP_CLASSIFICACAO_DOCUMENTO is
'Indica o tipo de classificação do Documento (Recebido ou Expedido).
E - EXPEDIDO
R - RECEBIDO
';

comment on column SAAD.DOCUMENTO_UNIDADE.TP_ORIGEM is
'Indica o tipo de origem.
I - INTERNO
E - EXTERNO';

comment on column SAAD.DOCUMENTO_UNIDADE.ID_DOCUMENTO_STJ is
'Identificador do Documento do STJ.';

comment on column SAAD.DOCUMENTO_UNIDADE.NR_DOCUMENTO_ORIGEM is
'Número do Documento Origem.';

comment on column SAAD.DOCUMENTO_UNIDADE.DT_DOCUMENTO_ORIGEM is
'Data do Documento Origem.';

comment on column SAAD.DOCUMENTO_UNIDADE.DT_RECEBIMENTO_EXPEDICAO is
'Data do Documento Recebido ou Expedido.';

comment on column SAAD.DOCUMENTO_UNIDADE.DH_INCLUSAO_DOCUMENTO is
'Data de Inclusao.';

comment on column SAAD.DOCUMENTO_UNIDADE.NR_PROCESSO_ADMINISTRATIVO is
'Número do processo administrativo.';

comment on column SAAD.DOCUMENTO_UNIDADE.TX_ASSUNTO_DOCUMENTO is
'Descrição do assunto do documento.';

comment on column SAAD.DOCUMENTO_UNIDADE.ST_DOCUMENTO_EVENTO is
'Indica se existe ou não um evento associado ao documento. Ex: reunião, palestra, convite.
S - SIM
N - NAO';

comment on column SAAD.DOCUMENTO_UNIDADE.ST_SITUACAO_DOCUMENTO is
'Indica a situação do documento. 
P - PENDENTE
R - RESOLVIDO
S - SUSPENSO
C - CANCELADO';

comment on column SAAD.DOCUMENTO_UNIDADE.SEQ_DESTINATARIO is
'Representa o vínculo com do SEQ_DESTINATARIO do banco MALADIR.';

--==============================================================
-- Index: IX_DOUN_SQ_TIPO_DO
--==============================================================
create index SAAD.IX_DOUN_SQ_TIPO_DO on SAAD.DOCUMENTO_UNIDADE (
   SQ_TIPO_DOCUMENTO    ASC
);

--==============================================================
-- Index: IX_DOUN_SEQ_LOCAL
--==============================================================
create index SAAD.IX_DOUN_SEQ_LOCAL on SAAD.DOCUMENTO_UNIDADE (
   SEQ_LOCAL            ASC
);

--==============================================================
-- Index: IX_DOUN_SQ_ENDEREC
--==============================================================
create index SAAD.IX_DOUN_SQ_ENDEREC on SAAD.DOCUMENTO_UNIDADE (
   SQ_ENDERECAMENTO     ASC
);

--==============================================================
-- Index: IX_DOUN_NUM_REGIST
--==============================================================
create index SAAD.IX_DOUN_NUM_REGIST on SAAD.DOCUMENTO_UNIDADE (
   NUM_REGISTRO         ASC
);

--==============================================================
-- Index: IX_DOUN_SEQ_DESTIN
--==============================================================
create index SAAD.IX_DOUN_SEQ_DESTIN on SAAD.DOCUMENTO_UNIDADE (
   SEQ_DESTINATARIO     ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.DOCUMENTO_UNIDADE to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: ENDERECAMENTO
--==============================================================
create table SAAD.ENDERECAMENTO
(
   SQ_ENDERECAMENTO     INTEGER                not null generated by default as identity,
   TP_ENDERECAMENTO     CHAR(3)                not null
      constraint CK_ENDE_TP_ENDERECAMENTO check (TP_ENDERECAMENTO in ('EIN','EMD','EOD')),
   NM_ENDERECADO        VARCHAR(150)           not null,
   constraint PK_ENDERECAMENTO primary key (SQ_ENDERECAMENTO)
);

comment on column SAAD.ENDERECAMENTO.SQ_ENDERECAMENTO is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.ENDERECAMENTO.TP_ENDERECAMENTO is
'Indica o tipo de endereçamento do usuário.
EIN - ENDEREÇAMENTO INTERNO
EMD - ENDEREÇAMENTO PARA DESTINATÁRIO DO MALA DIRETA
EOD - ENDEREÇAMENTO PARA OUTRO DESTINATÁRIO';

comment on column SAAD.ENDERECAMENTO.NM_ENDERECADO is
'Nome do rementente ou destinatário.';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.ENDERECAMENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: ENDERECAMENTO_EXTERNO
--==============================================================
create table SAAD.ENDERECAMENTO_EXTERNO
(
   SQ_ENDERECAMENTO     INTEGER                not null,
   SEQ_DESTINATARIO     INTEGER                not null,
   constraint PK_ENDERECAMENTO_EXTERNO primary key (SQ_ENDERECAMENTO)
);

comment on column SAAD.ENDERECAMENTO_EXTERNO.SQ_ENDERECAMENTO is
'Definição de chave estrangeira. Tabela ENDERECAMENTO.';

comment on column SAAD.ENDERECAMENTO_EXTERNO.SEQ_DESTINATARIO is
'Representa o vínculo com do SEQ_DESTINATARIO do banco MALADIR.
Identifica o endereço do usuário externo.';

--==============================================================
-- Index: IX_ENEX_SEQ_DESTIN
--==============================================================
create index SAAD.IX_ENEX_SEQ_DESTIN on SAAD.ENDERECAMENTO_EXTERNO (
   SEQ_DESTINATARIO     ASC
);

--==============================================================
-- Index: IX_ENEX_SQ_DESTINA
--==============================================================
create index SAAD.IX_ENEX_SQ_DESTINA on SAAD.ENDERECAMENTO_EXTERNO (

);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.ENDERECAMENTO_EXTERNO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: ENDERECAMENTO_INTERNO
--==============================================================
create table SAAD.ENDERECAMENTO_INTERNO
(
   SQ_ENDERECAMENTO     INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   constraint PK_ENDERECAMENTO_INTERNO primary key (SQ_ENDERECAMENTO)
);

comment on column SAAD.ENDERECAMENTO_INTERNO.SQ_ENDERECAMENTO is
'Definição de chave estrangeira. Tabela ENDERECAMENTO.';

comment on column SAAD.ENDERECAMENTO_INTERNO.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

--==============================================================
-- Index: IX_ENIN_SEQ_LOCAL
--==============================================================
create index SAAD.IX_ENIN_SEQ_LOCAL on SAAD.ENDERECAMENTO_INTERNO (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.ENDERECAMENTO_INTERNO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: EVENTO
--==============================================================
create table SAAD.EVENTO
(
   SQ_EVENTO            INTEGER                not null,
   NM_EVENTO            VARCHAR(150)           not null,
   DT_INICIO_EVENTO     DATE                   not null,
   DT_TERMINO_EVENTO    DATE                   not null,
   TX_OBSERVACAO_EVENTO CLOB(2097152),
   NR_CARGA_HORARIA_TOTAL INTEGER                not null,
   HR_INICIO_EVENTO     TIME                   not null,
   HR_TERMINO_EVENTO    TIME                   not null,
   constraint PK_EVENTO primary key (SQ_EVENTO)
);

comment on column SAAD.EVENTO.SQ_EVENTO is
'Definição de chave estrangeira. Tabela DOCUMENTO_UNIDADE.';

comment on column SAAD.EVENTO.NM_EVENTO is
'Nome do Evento.';

comment on column SAAD.EVENTO.DT_INICIO_EVENTO is
'Data Início do Evento.';

comment on column SAAD.EVENTO.DT_TERMINO_EVENTO is
'Data término do Evento.';

comment on column SAAD.EVENTO.TX_OBSERVACAO_EVENTO is
'Observação relacionada ao Evento.';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.EVENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: METADADO_AUTORIZADO
--==============================================================
create table SAAD.METADADO_AUTORIZADO
(
   SQ_CAMPO_PERSONALIZADO NUMERIC(6, 0)          not null,
   SEQ_LOCAL            INTEGER                not null,
   ST_PREENCHIMENTO_OBRIGATORIO CHAR(1)                not null default 'N'
      constraint CK_MEAU_ST_PREENCHIMENTO_OBRIG check (ST_PREENCHIMENTO_OBRIGATORIO in ('S','N')),
   constraint PK_METADADO_AUTORIZADO primary key (SQ_CAMPO_PERSONALIZADO, SEQ_LOCAL)
);

comment on column SAAD.METADADO_AUTORIZADO.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

--==============================================================
-- Index: IX_MEAU_SEQ_LOCAL
--==============================================================
create index SAAD.IX_MEAU_SEQ_LOCAL on SAAD.METADADO_AUTORIZADO (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.METADADO_AUTORIZADO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: RESERVA_NUMERACAO_DOC
--==============================================================
create table SAAD.RESERVA_NUMERACAO_DOC
(
   SQ_RESERVA_NUMERACAO_DOC INTEGER                not null generated by default as identity,
   SQ_TIPO_DOCUMENTO    INTEGER                not null,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   SEQ_LOCAL            INTEGER,
   NR_ANO               INTEGER                not null,
   NR_RESERVADO         INTEGER                not null,
   DH_RESERVA           TIMESTAMP              not null,
   constraint PK_RESERVA_NUMERACAO_DOC primary key (SQ_RESERVA_NUMERACAO_DOC)
);

comment on column SAAD.RESERVA_NUMERACAO_DOC.SQ_DOCUMENTO_UNIDADE is
'Definição de chave estrangeira. Tabela DOCUMENTO_UNIDADE.';

comment on column SAAD.RESERVA_NUMERACAO_DOC.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

comment on column SAAD.RESERVA_NUMERACAO_DOC.NR_ANO is
'Número do ano.';

comment on column SAAD.RESERVA_NUMERACAO_DOC.NR_RESERVADO is
'Número(s) reservado(s) para';

comment on column SAAD.RESERVA_NUMERACAO_DOC.DH_RESERVA is
'Data da reserva do(s) número(s).';

--==============================================================
-- Index: IX_RENU_SQ_TIPO_DO
--==============================================================
create index SAAD.IX_RENU_SQ_TIPO_DO on SAAD.RESERVA_NUMERACAO_DOC (
   SQ_TIPO_DOCUMENTO    ASC
);

--==============================================================
-- Index: IX_RENU_SQ_DOCUMEN
--==============================================================
create index SAAD.IX_RENU_SQ_DOCUMEN on SAAD.RESERVA_NUMERACAO_DOC (
   SQ_DOCUMENTO_UNIDADE ASC
);

--==============================================================
-- Index: IX_RENU_SEQ_LOCAL
--==============================================================
create index SAAD.IX_RENU_SEQ_LOCAL on SAAD.RESERVA_NUMERACAO_DOC (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.RESERVA_NUMERACAO_DOC to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: TAREFA_DEMANDA_DOCUMENTO
--==============================================================
create table SAAD.TAREFA_DEMANDA_DOCUMENTO
(
   SQ_TAREFA            INTEGER                not null generated by default as identity,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   SEQ_USUARIO          INTEGER                not null,
   DS_TAREFA            CLOB(2056)             not null,
   DT_LIMITE_CONCLUSAO  DATE                   not null,
   ST_TAREFA            CHAR(1)                not null default 'P'
      constraint CK_TADD_ST_TAREFA check (ST_TAREFA in ('P','R')),
   DT_CONCLUSAO_TAREFA  DATE,
   DH_INCLUSAO_TAREFA   TIMESTAMP              not null,
   constraint PK_TAREFA_DEMANDA_DOCUMENTO primary key (SQ_TAREFA)
);

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.SQ_TAREFA is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.SQ_DOCUMENTO_UNIDADE is
'Definição de chave estrangeira. Tabela DOCUMENTO_UNIDADE.';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.SEQ_USUARIO is
'Representa o vínculo com o SEQ_USUARIO do banco JUSTIÇA COMUNS.';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.DS_TAREFA is
'Descrição da tarefa.';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.DT_LIMITE_CONCLUSAO is
'Data limite da conclusão da demanda.';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.ST_TAREFA is
'Indica a situação da tarefa. 
P - PENDENTE
R - RESOLVIDO';

comment on column SAAD.TAREFA_DEMANDA_DOCUMENTO.DT_CONCLUSAO_TAREFA is
'Data da conclusão da demanda.';

--==============================================================
-- Index: IX_TADD_SQ_DOCUMEN
--==============================================================
create index SAAD.IX_TADD_SQ_DOCUMEN on SAAD.TAREFA_DEMANDA_DOCUMENTO (
   SQ_DOCUMENTO_UNIDADE ASC
);

--==============================================================
-- Index: IX_TADD_SEQ_USUARI
--==============================================================
create index SAAD.IX_TADD_SEQ_USUARI on SAAD.TAREFA_DEMANDA_DOCUMENTO (
   SEQ_USUARIO          ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.TAREFA_DEMANDA_DOCUMENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: TIPO_DOCUMENTO
--==============================================================
create table SAAD.TIPO_DOCUMENTO
(
   SQ_TIPO_DOCUMENTO    INTEGER                not null generated by default as identity,
   NM_TIPO_DOCUMENTO    VARCHAR(150)           not null,
   SG_TIPO_DOCUMENTO    CHAR(3)                not null,
   ST_RELATIVO_PROCESSO CHAR(1)                not null default 'N'
      constraint CK_TIDO_ST_RELATIVO_PROCESSO check (ST_RELATIVO_PROCESSO in ('N','J','A')),
   constraint PK_TIPO_DOCUMENTO primary key (SQ_TIPO_DOCUMENTO)
);

comment on column SAAD.TIPO_DOCUMENTO.SQ_TIPO_DOCUMENTO is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.TIPO_DOCUMENTO.NM_TIPO_DOCUMENTO is
'Nome do tipo de documento.';

comment on column SAAD.TIPO_DOCUMENTO.SG_TIPO_DOCUMENTO is
'Sigla do tipo de documento.';

comment on column SAAD.TIPO_DOCUMENTO.ST_RELATIVO_PROCESSO is
'Indica a situação relativo ao processo
N - NAO
J - JUDICIAL
A - ADMINISTRATIVO
';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.TIPO_DOCUMENTO to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: TIPO_DOCUMENTO_UNIDADE
--==============================================================
create table SAAD.TIPO_DOCUMENTO_UNIDADE
(
   SQ_TIPO_DOCUMENTO    INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   NM_CAMINHO_PASTA_FISICA VARCHAR(255),
   ST_GESTAO_MINISTRO   CHAR(1)                not null default 'N'
      constraint CK_TIDU_ST_GESTAO_MINISTRO check (ST_GESTAO_MINISTRO in ('S','N')),
   constraint PK_TIPO_DOCUMENTO_UNIDADE primary key (SQ_TIPO_DOCUMENTO, SEQ_LOCAL)
);

comment on column SAAD.TIPO_DOCUMENTO_UNIDADE.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

comment on column SAAD.TIPO_DOCUMENTO_UNIDADE.NM_CAMINHO_PASTA_FISICA is
'Onde salva o arquivo de cada tipo de documento.';

--==============================================================
-- Index: IX_TIDU_SEQ_LOCAL
--==============================================================
create index SAAD.IX_TIDU_SEQ_LOCAL on SAAD.TIPO_DOCUMENTO_UNIDADE (
   SEQ_LOCAL            ASC
);

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.TIPO_DOCUMENTO_UNIDADE to RL_SAAD_GERENTE_WEB;

--==============================================================
-- Table: VALOR_METADADO
--==============================================================
create table SAAD.VALOR_METADADO
(
   SQ_DOCUMENTO_UNIDADE INTEGER                not null,
   SQ_CAMPO_PERSONALIZADO NUMERIC(6, 0)          not null,
   SEQ_LOCAL            INTEGER                not null,
   TX_VALOR_METADADO    VARCHAR(255)           not null,
   constraint PK_VALOR_METADADO primary key (SQ_DOCUMENTO_UNIDADE, SQ_CAMPO_PERSONALIZADO, SEQ_LOCAL)
);

comment on column SAAD.VALOR_METADADO.SEQ_LOCAL is
'Representa o vínculo com do SEQ_LOCAL do banco JUSTIÇA COMUNS.
Identifica a unidade do STJ.';

--==============================================================
-- Index: IX_VAME_SQ_CAMPO_P
--==============================================================
create index SAAD.IX_VAME_SQ_CAMPO_P on SAAD.VALOR_METADADO (
   SQ_CAMPO_PERSONALIZADO ASC,
   SEQ_LOCAL            ASC
);


alter table SAAD.ANDAMENTO_DOCUMENTO
   add constraint FK_ANDO_DOUN foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.ANDAMENTO_DOCUMENTO
   add constraint FK_ANDO_USUARIO foreign key (SEQ_USUARIO)
      references DB2SA.USUARIO (SEQ_USUARIO)
      on delete restrict on update restrict;

alter table SAAD.ANEXO
   add constraint FK_ANEXO_DOCUMENTO_UNIDADE foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.AVISO_UNIDADE
   add constraint FK_AVUN_DOCUMENTO_UNIDADE foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.AVISO_UNIDADE
   add constraint FK_AVUN_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.CAMPO_PERSONALIZADO
   add constraint FK_CAPE_TIDO foreign key (SQ_TIPO_DOCUMENTO)
      references SAAD.TIPO_DOCUMENTO (SQ_TIPO_DOCUMENTO)
      on delete restrict on update restrict;

alter table SAAD.CONTROLE_NUMERACAO
   add constraint FK_CONTROLE_NUMERACAO_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.CONTROLE_NUMERACAO
   add constraint FK_CONTROLE_NUMERACAO_TIDU foreign key (SQ_TIPO_DOCUMENTO)
      references SAAD.TIPO_DOCUMENTO (SQ_TIPO_DOCUMENTO)
      on delete restrict on update restrict;

alter table SAAD.DESTINATARIO_AVISO
   add constraint FK_DEAV_AVISO_UNIDADE foreign key (SQ_AVISO_UNIDADE)
      references SAAD.AVISO_UNIDADE (SQ_AVISO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.DESTINATARIO_AVISO
   add constraint FK_DESTINATARIO_AVISO_USUARIO foreign key (SEQ_USUARIO)
      references DB2SA.USUARIO (SEQ_USUARIO)
      on delete restrict on update restrict;

alter table SAAD.DESTINATARIO_DOCUMENTO
   add constraint FK_DEDO_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.DESTINATARIO_DOCUMENTO
   add constraint FK_DEDO_TRATAMENTO foreign key (SEQ_TRATAMENTO)
      references MALADIR.TRATAMENTO (SEQ_TRATAMENTO)
      on delete restrict on update restrict;

alter table SAAD.DESTINATARIO_DOCUMENTO
   add constraint FK_DEST_DOCUMENTO_UNIDADE foreign key (SQ_DESTINATARIO_DOCUMENTO)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.DOCUMENTO_UNIDADE
   add constraint FK_DOCUMENTO_UNIDADE_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.DOCUMENTO_UNIDADE
   add constraint FK_DOCUMENTO_UNIDADE_PROCESSO foreign key (NUM_REGISTRO)
      references DB2SA.PROCESSO (NUM_REGISTRO)
      on delete restrict on update restrict;

alter table SAAD.DOCUMENTO_UNIDADE
   add constraint FK_DOUN_DESTINATARIO foreign key (SEQ_DESTINATARIO)
      references MALADIR.DESTINATARIO (SEQ_DESTINATARIO)
      on delete restrict on update restrict;

alter table SAAD.DOCUMENTO_UNIDADE
   add constraint FK_DOUN_ENDERECAMENTO foreign key (SQ_ENDERECAMENTO)
      references SAAD.ENDERECAMENTO (SQ_ENDERECAMENTO)
      on delete restrict on update restrict;

alter table SAAD.DOCUMENTO_UNIDADE
   add constraint FK_DOCUMENTO_TIPO_DOCUMENTO foreign key (SQ_TIPO_DOCUMENTO)
      references SAAD.TIPO_DOCUMENTO (SQ_TIPO_DOCUMENTO)
      on delete restrict on update restrict;

alter table SAAD.ENDERECAMENTO_EXTERNO
   add constraint FK_ENEX_DESTINATARIO foreign key (SEQ_DESTINATARIO)
      references MALADIR.DESTINATARIO (SEQ_DESTINATARIO)
      on delete restrict on update restrict;

alter table SAAD.ENDERECAMENTO_EXTERNO
   add constraint FK_ENEX_ENDERECAMENTO foreign key (SQ_ENDERECAMENTO)
      references SAAD.ENDERECAMENTO (SQ_ENDERECAMENTO)
      on delete restrict on update restrict;

alter table SAAD.ENDERECAMENTO_INTERNO
   add constraint FK_ENIN_ENDERECAMENTO foreign key (SQ_ENDERECAMENTO)
      references SAAD.ENDERECAMENTO (SQ_ENDERECAMENTO)
      on delete restrict on update restrict;

alter table SAAD.ENDERECAMENTO_INTERNO
   add constraint FK_ENIN_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.EVENTO
   add constraint FK_DOEV_DOUN foreign key (SQ_EVENTO)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.METADADO_AUTORIZADO
   add constraint FK_MEAU_CAPE foreign key (SQ_CAMPO_PERSONALIZADO)
      references SAAD.CAMPO_PERSONALIZADO (SQ_CAMPO_PERSONALIZADO)
      on delete restrict on update restrict;

alter table SAAD.METADADO_AUTORIZADO
   add constraint F_FK_MEAU_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.RESERVA_NUMERACAO_DOC
   add constraint FK_REND_DOUN foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.RESERVA_NUMERACAO_DOC
   add constraint FK_REND_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.RESERVA_NUMERACAO_DOC
   add constraint FK_REND_TIDU foreign key (SQ_TIPO_DOCUMENTO)
      references SAAD.TIPO_DOCUMENTO (SQ_TIPO_DOCUMENTO)
      on delete restrict on update restrict;

alter table SAAD.TAREFA_DEMANDA_DOCUMENTO
   add constraint FK_TADD_DOCUMENTO_UNIDADE foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.TAREFA_DEMANDA_DOCUMENTO
   add constraint FK_TADD_USUARIO foreign key (SEQ_USUARIO)
      references DB2SA.USUARIO (SEQ_USUARIO)
      on delete restrict on update restrict;

alter table SAAD.TIPO_DOCUMENTO_UNIDADE
   add constraint F_FK_TIDU_LOCAL foreign key (SEQ_LOCAL)
      references DB2SA."LOCAL" (SEQ_LOCAL)
      on delete restrict on update restrict;

alter table SAAD.TIPO_DOCUMENTO_UNIDADE
   add constraint FK_TIDU_TIDO foreign key (SQ_TIPO_DOCUMENTO)
      references SAAD.TIPO_DOCUMENTO (SQ_TIPO_DOCUMENTO)
      on delete restrict on update restrict;

alter table SAAD.VALOR_METADADO
   add constraint FK_VAME_DOUN foreign key (SQ_DOCUMENTO_UNIDADE)
      references SAAD.DOCUMENTO_UNIDADE (SQ_DOCUMENTO_UNIDADE)
      on delete restrict on update restrict;

alter table SAAD.VALOR_METADADO
   add constraint FK_VAME_MEAU foreign key (SQ_CAMPO_PERSONALIZADO, SEQ_LOCAL)
      references SAAD.METADADO_AUTORIZADO (SQ_CAMPO_PERSONALIZADO, SEQ_LOCAL)
      on delete restrict on update restrict;
