drop table SAAD.AUDIT_DOCUMENTO_UNIDADE;

--==============================================================
-- Table: AUDIT_DOCUMENTO_UNIDADE
--==============================================================
create table SAAD.AUDIT_DOCUMENTO_UNIDADE
(
   SQ_AUDIT_DOCUMENTO_UNIDADE INTEGER                not null generated by default as identity,
   SEQ_USUARIO          INTEGER                not null,
   DH_OPERACAO          DATE                   not null,
   TP_OPERACAO          CHAR(1)                not null
      constraint CK_AUDU_TP_OPERACAO check (TP_OPERACAO in ('I','E','A')),
   SQ_DOCUMENTO_UNIDADE INTEGER                not null,
   SQ_TIPO_DOCUMENTO_UNIDADE INTEGER                not null,
   SEQ_LOCAL            INTEGER                not null,
   NUM_REGISTRO         CHARACTER(12),
   SQ_ENDERECAMENTO     INTEGER,
   TP_CLASSIFICACAO_DOCUMENTO CHAR(1)                not null
      constraint CK_AUDU_TP_CLASSIFICACAO check (TP_CLASSIFICACAO_DOCUMENTO in ('E','R')),
   TP_ORIGEM            CHAR(1)                not null
      constraint CK_AUDU_TP_ORIGEM check (TP_ORIGEM in ('I','E')),
   ID_DOCUMENTO_STJ     VARCHAR(6)             not null,
   NR_DOCUMENTO_ORIGEM  VARCHAR(20)            not null,
   DH_DOCUMENTO_ORIGEM  DATE                   not null,
   DH_RECEBIMENTO_EXPEDICAO DATE,
   DH_INCLUSAO          DATE,
   NR_PROCESSO_ADMINISTRATIVO VARCHAR(30),
   TX_ASSUNTO_DOCUMENTO CLOB(2096)             not null,
   ST_DOCUMENTO_EVENTO  CHAR(1)                not null default 'N'
      constraint CK_AUDU_ST_DOCUMENTO_EVENTO check (ST_DOCUMENTO_EVENTO in ('S','N')),
   ST_SITUACAO_DOCUMENTO CHAR(1)                not null default 'P'
      constraint CK_AUDU_ST_SITUACAO_DOCUMENTO check (ST_SITUACAO_DOCUMENTO in ('P','R','S','C')),
   SEQ_DESTINATARIO     INTEGER,
   constraint PK_AUDIT_DOCUMENTO_UNIDADE primary key (SQ_AUDIT_DOCUMENTO_UNIDADE)
);

comment on table SAAD.AUDIT_DOCUMENTO_UNIDADE is
'Entidade que mantém a auditoria do documento da unidade.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SQ_AUDIT_DOCUMENTO_UNIDADE is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SEQ_USUARIO is
'Identifica o usuário que fez  a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.DH_OPERACAO is
'Hora da operação que o usuário que fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.TP_OPERACAO is
'Indica o tipo de operação que o usuário fez no sistema.
I - INCLUSÃO
A - ALTERAÇÃO
E - EXCLUSÃO
';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SQ_DOCUMENTO_UNIDADE is
'Identifica o documento da unidade que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SQ_TIPO_DOCUMENTO_UNIDADE is
'Identifica o tipo documento da unidade que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SEQ_LOCAL is
'Identifica o local da unidade que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.NUM_REGISTRO is
'Número do registro que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SQ_ENDERECAMENTO is
'Identifica o enderecamento que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.TP_CLASSIFICACAO_DOCUMENTO is
'Indica o tipo de classificação do documento que o usuário fez no sistema.
E - EXPEDIDO
R - RECEBIDO';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.TP_ORIGEM is
'Indica a origem do documento que o usuário fez no sistema.
I - INTERNO
E - EXTERNO';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.ID_DOCUMENTO_STJ is
'Número identificado do STJ que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.NR_DOCUMENTO_ORIGEM is
'Número de origem do documento que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.DH_DOCUMENTO_ORIGEM is
'Data da origem do documento que o usuário fez a ação de  inclusões, alterações e/ou exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.DH_RECEBIMENTO_EXPEDICAO is
'Data do recebimento da expedição que o usuário fez a ação de inclusões, alterações e/ou exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.DH_INCLUSAO is
'Data de inclusão que o usuário  fez a ação de inclusões, alterações e/ou exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.NR_PROCESSO_ADMINISTRATIVO is
'Número do processo administrativo que o usuário  fez a ação de inclusões, alterações e/ou exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.TX_ASSUNTO_DOCUMENTO is
'Descrição do assunto do documento que o usuário  fez a ação de inclusões, alterações e/ou exclusões no sistema.';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.ST_DOCUMENTO_EVENTO is
'Indica se existe ou não um evento associado ao documento que o usuário  fez a ação de inclusões, alterações e/ou exclusões no sistema.
S - SIM
N - NAO';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.ST_SITUACAO_DOCUMENTO is
'Indica a situação do documento que o usuário  fez a ação de inclusões, alterações e/ou exclusões no sistema.
P - PENDENTE
R - RESOLVIDO
S - SUSPENSO
C - CANCELADO';

comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.SEQ_DESTINATARIO is
'Identifica o destinatário o usuário que fez a ação de inclusões, alterações e/ou exclusões no sistema.';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.AUDIT_DOCUMENTO_UNIDADE to RL_SAAD_GERENTE_WEB;
