--==============================================================
-- Table: AUDIT_DOCUMENTO_UNIDADE
--==============================================================
ALTER TABLE SAAD.AUDIT_DOCUMENTO_UNIDADE ADD TX_PASTA_FISICA VARCHAR(50);
comment on column SAAD.AUDIT_DOCUMENTO_UNIDADE.TX_PASTA_FISICA is 'Descrição do local onde guarda o fichário fisíco.';

--==============================================================
-- Table: AUDIT_ANDAMENTO_DOCUMENTO
--==============================================================
create table SAAD.AUDIT_ANDAMENTO_DOCUMENTO
(
   AUDIT_ANDAMENTO_DOCUMENTO INTEGER                not null generated by default as identity,
   SEQ_USUARIO          INTEGER                not null,
   DH_OPERACAO          DATE                   not null,
   TP_OPERACAO          CHAR(1)                not null
      constraint C_TP_OPERACAO check (TP_OPERACAO in ('I','A','E')),
   SQ_ANDAMENTO_DOCUMENTO INTEGER                not null,
   SQ_DOCUMENTO_UNIDADE INTEGER,
   DS_ANDAMENTO_DOCUMENTO CLOB(2097152)          not null,
   DH_ANDAMENTO_DOCUMENTO DATE                   not null,
   constraint P_PK_AUDIT_ANDAMEN primary key (AUDIT_ANDAMENTO_DOCUMENTO)
);

comment on table SAAD.AUDIT_ANDAMENTO_DOCUMENTO is
'Entidade que mantém a auditoria do andamento do documento';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.AUDIT_ANDAMENTO_DOCUMENTO is
'Definição de chave primária. Número identificador gerado pelo sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.SEQ_USUARIO is
'Identifica o usuário que fez  a ação de inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.DH_OPERACAO is
'Data da operação que o usuário que fez a ação de inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.TP_OPERACAO is
'Indica o tipo de operação que o usuário fez no sistema.
I - INCLUSÃO
A - ALTERAÇÃO
E - EXCLUSÃO';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.SQ_ANDAMENTO_DOCUMENTO is
'Identifica o andamento do documento que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.SQ_DOCUMENTO_UNIDADE is
'Identifica o documento da unidade que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.DS_ANDAMENTO_DOCUMENTO is
'Descrição do andamento do documento que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

comment on column SAAD.AUDIT_ANDAMENTO_DOCUMENTO.DH_ANDAMENTO_DOCUMENTO is
'Data do andamento do documento que o usuário fez a ação inclusões, alterações e exclusões no sistema.';

grant DELETE,INSERT,SELECT,UPDATE,REFERENCES on SAAD.AUDIT_DOCUMENTO_UNIDADE to RL_SAAD_GERENTE_WEB;
